server:
  port: 8088

spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  cloud:
    config:
      profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/department
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate-dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: validate

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  service-url:
    defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost