server:
  port: 8088

spring:
  application:
    name: DEPARTMENT-SERVICE
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:postgresql://localhost:5432/department
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    properties:
      hibernate-dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
  zipkin:
    base-url: http://localhost:9411/

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka
